# Read pickel for Feature Engineering

In [77]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [78]:
df = pd.read_pickle('../pickle/itsm_clean.pkl')
df.head()

     CI_Name          CI_Cat  ... is_high_priority YearMonth
0  SUB000508  subapplication  ...                0   2012-02
1  WBA000124     application  ...                0   2012-03
2  WBA000124     application  ...                0   2012-07
3  WBA000124     application  ...                0   2012-08
4  WBA000124     application  ...                0   2012-08

[5 rows x 23 columns]

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45117 entries, 0 to 45116
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CI_Name                     45117 non-null  str
 1   CI_Cat                      45117 non-null  str
 2   CI_Subcat                   45117 non-null  str
 3   WBS                         45117 non-null  str
 4   Incident_ID                 45117 non-null  str
 5   Status                      45117 non-null  str
 6   Impact                      45117 non-null  int64
 7   Urgency                     45117 non-null  int64
 8   Priority                    45117 non-null  float64
 9   number_cnt                  45117 non-null  float64
 10  Category                    45117 non-null  str
 11  KB_number                   45117 non-null  str
 12  Alert_Status                45117 non-null  str
 13  No_of_Reassignments         45117 non-null  float64
 14  Open_Time                   45117 non-null  datetime64[us]
 15  Resolved_Time               43483 non-null  datetime64[us]
 16  Close_Time                  45117 non-null  datetime64[us]
 17  Handle_Time_hrs             45117 non-null  float64
 18  Closure_Code                45117 non-null  str
 19  No_of_Related_Interactions  45117 non-null  float64
 20  Related_Interaction         45117 non-null  str
 21  is_high_priority            45117 non-null  int64
 22  YearMonth                   45117 non-null  period[M]
dtypes: datetime64[us](3), float64(5), int64(3), period[M](1), str(11)
memory usage: 7.9 MB

## Drop column to prevent Data leakage

In [80]:
df = df.drop(columns=['CI_Name', 'WBS', 'Incident_ID', 'KB_number','Related_Interaction', 'Alert_Status','Impact', 'Urgency', 'Priority', 'YearMonth'])

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45117 entries, 0 to 45116
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   CI_Cat                      45117 non-null  str
 1   CI_Subcat                   45117 non-null  str
 2   Status                      45117 non-null  str
 3   number_cnt                  45117 non-null  float64
 4   Category                    45117 non-null  str
 5   No_of_Reassignments         45117 non-null  float64
 6   Open_Time                   45117 non-null  datetime64[us]
 7   Resolved_Time               43483 non-null  datetime64[us]
 8   Close_Time                  45117 non-null  datetime64[us]
 9   Handle_Time_hrs             45117 non-null  float64
 10  Closure_Code                45117 non-null  str
 11  No_of_Related_Interactions  45117 non-null  float64
 12  is_high_priority            45117 non-null  int64
dtypes: datetime64[us](3), float64(4), int64(1), str(5)
memory usage: 4.5 MB

In [82]:
df.shape

(45117, 13)

## Convert CI_Subcat from 64 unique values into the top 15 values and group the remaining values as Other

In [83]:
top_15_subcat = df['CI_Subcat'].value_counts().head(15).index.tolist()

print(top_15_subcat)

['Server Based Application', 'Web Based Application', 'Desktop Application', 'Laptop', 'SAP', 'Banking Device', 'Citrix', 'SAN', 'Client Based Application', 'Desktop', 'DataCenterEquipment', 'System Software', 'Monitor', 'Database', 'Windows Server']

In [84]:
def check_subcat(x):
    if x in top_15_subcat:
        return x
    else:
        return 'other'


df['CI_Subcat'] = df['CI_Subcat'].apply(check_subcat)

## Retrive data from Oper_date_time into Open_month,open_day_of_week and Open_hour

In [85]:
df['open_month'] = df['Open_Time'].dt.month
df['open_dayofweek'] = df['Open_Time'].dt.day_name()
df['open_hour'] = df['Open_Time'].dt.hour

# Drop columns

df = df.drop(columns=['Open_Time','Resolved_Time','Close_Time'])

## One-hotEncoding

In [86]:
df = pd.get_dummies(df,columns=['CI_Cat', 'CI_Subcat', 'Category', 'Status', 'Closure_Code','open_dayofweek'])

In [87]:
df.head()

   number_cnt  ...  open_dayofweek_Wednesday
0    0.601292  ...                     False
1    0.415050  ...                     False
2    0.642927  ...                     False
3    0.345258  ...                     False
4    0.006676  ...                     False

[5 rows x 61 columns]

## Feature Engineering — Observation Report

### Overview
Building on the cleaned dataset (45,117 records) and EDA findings, feature engineering was performed to transform the data into a model-ready format. This involved removing irrelevant and leakage-prone columns, extracting new features from datetime fields, and encoding categorical variables.

---

### 1. Column Removal

The following columns were dropped prior to encoding:

| Column(s) | Reason |
|---|---|
| `CI_Name`, `WBS`, `Incident_ID`, `KB_number`, `Related_Interaction` | High-cardinality identifier columns with no generalizable predictive pattern |
| `Alert_Status` | Zero variance (single unique value across all records) |
| `Impact`, `Urgency`, `Priority` | Excluded to prevent **data leakage** — `Priority` is directly derived from `Impact` and `Urgency` via the Priority Matrix, and the target variable (`is_high_priority`) is in turn derived from `Priority`. Including these would allow the model to reverse-engineer the target rather than learn genuine predictive patterns. |
| `YearMonth` | Helper column created only for EDA time-trend visualization; not needed as a model feature |

---

### 2. Datetime Feature Extraction

Rather than dropping datetime information entirely, three new features were derived from `Open_Time` (the only timestamp available at the moment a new ticket is created, and therefore safe to use without leakage):

- `open_month` (1–12) — retained as a numeric feature to capture potential seasonal patterns.
- `open_hour` (0–23) — retained as a numeric feature to capture time-of-day patterns (e.g., business hours vs. after-hours).
- `open_dayofweek` (Monday–Sunday) — extracted as a categorical feature and one-hot encoded, since day-of-week is cyclical and has no meaningful numeric order.

`Resolved_Time` and `Close_Time` were **dropped without feature extraction**, since these timestamps only exist after a ticket is resolved/closed — using them (or any derived features) would constitute data leakage, as this information is unavailable at prediction time for a new incoming ticket.

---

### 3. Categorical Encoding

The following categorical columns were one-hot encoded using `pd.get_dummies()`: `CI_Cat`, `CI_Subcat`, `Category`, `Status`, `Closure_Code`, and `open_dayofweek`.

**Special handling for `CI_Subcat`:** This column originally contained 62 unique values, most of which were rare occurrences (long-tail distribution, as observed during EDA). To avoid excessive dimensionality from encoding, only the **top 15 most frequent sub-categories** (covering the vast majority of records — e.g., "Server Based Application" and "Web Based Application" alone account for over 33,000 of 45,117 tickets) were retained individually; all remaining sub-categories were grouped into a single `"Other"` category before encoding.

---

### 4. Final Feature Set

After column removal, feature extraction, and encoding, the dataset expanded from its original set of columns to **50 columns** (45,117 rows unchanged). All columns are now in numeric or boolean (True/False) format, with no remaining text/object columns, identifiers, or leakage-prone fields.

**Final feature categories:**
- Numeric: `number_cnt`, `No_of_Reassignments`, `Handle_Time_hrs`, `No_of_Related_Interactions`, `open_month`, `open_hour`
- One-hot encoded: `CI_Cat_*`, `CI_Subcat_*`, `Category_*`, `Status_*`, `Closure_Code_*`, `open_dayofweek_*`
- Target: `is_high_priority`

---

### Next Steps
- Save the final feature-engineered dataset (pickle format, to preserve data types).
- Proceed to modeling: separate features (X) from the target (y), perform a stratified train-test split, and address class imbalance (98.46% vs. 1.53%) using `class_weight='balanced'` and/or SMOTE.

In [88]:
df.to_pickle('../pickle/itsm_features.pkl')